dell-asm/vmware-vcenter

lib/puppet/provider/vc_vm/default.rb
Removed the check to avoid rebooting the VM in case of network definition change. In case on new port-group is added or a previous port-group is updated then the VM is rebooted
Without this change the VM do not have the network connectivity
=> ASM-2873 RHEL VM does not get network connectivity

lib/puppet/provider/esx_reconfigureha/default.rb
Previous code was only running the reconfigure HA task if the
dasHostState.state was fdmUnreachable. But there appear to be many
other cases where HA is not funcitoning properly, including if
dasHostState itself is nil.
=> ASM-4361 run reconfigure HA task in more cases

lib/puppet/provider/vc_vm/default.rb, lib/puppet/type/vc_vm.rb
handles the vm custom spec in the vc_vm provider module; vc_vm type is updated with the new param for the vm custom spec
=> ASM-2927: apply the spec to clone vm with the given vm_custom_spec name

lib/puppet/provider/vc_vm/default.rb
Spent a long time yesterday trying to figure out why VM creation
was failing because the ensure block was masking any thrown
exceptions.
=> Log VM creation errors

bin/discovery.rb
Also a quick fix for an issue where vendors might have an extra space after the name
=> ASM-5128 Added host name in inventory for host

lib/puppet/provider/vc_vm/default.rb
For clone VM scenario, datastore information was not getting passed as a result clusters having non-common datastore was failing. Also clone VM API needs datastore object instead of datastore name.
=> ASM-5147 Unable to clone across clusters under same datacenters.

lib/puppet/provider/vc_vm/default.rb
Added support for dvport-group mapping to the virtual machine in case the port-group name is provided in format "Portgroup (vds name)" and the VDS name exists on the datacenter
=> ASM-4969 VM deployment fails to find PXE portgroup

lib/puppet/provider/esx_datastore/default.rb
esx_datastore performing rescall operation which performs operation is async mode. In case there are multiple datastore or volumes that needs to be mapped to the server, timeout was getting observed.
Added  refresh storage and extending the sleep and retry counter to take care of the scenario
=> ASM-5644 Clusters failing in iSCSI deployments  IQN no-detected

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
Intermittently it is observed that initialization of VSAN disk is not getting triggered when there are multiple hosts in the VSAN cluster. Introduced a delay of 15 seconds to ensure success of the deployment.
=> ASM-5561 Server Puppet module changes for Phase 1 vSAN support for RA HCL

bin/discovery.rb
The error message was using a logger that didn't exist.
=> ASM-6156 Vmware inventory was failing if it couldn't find a host service tag

lib/puppet/provider/iscsi_intiator_binding/default.rb
iSCSI initiator mapping puppet resource is using esxcli commands for mapping vmkernel with software adapters. In case vmkernel is already binding to the software adapter, error was generated.
so far we were having one to mapping between iSCSI VMK and storage adapter thats why this error was not surfaced
with software initiator we need to map multiple vmkernel to same storage adapter.
=> ASM-6057 Management VNIC is not getting mapped correctly for VDS deployments

lib/puppet/provider/esx_maintmode/default.rb, lib/puppet/type/esx_maintmode.rb
VSAN Teardown moves the host to maintenance mode before removing the cluster disk groups. Currently we were not passing the VSAN maintenance behavior explicitly which was initiating the maintenance mode in 'ensureAccessibility". And this process is time-consuming and may result in errors during teardown.
Added "noAction" behavior to make sure VSAN teardown works without any additional validation.
=> ASM-5858 VSAN Teardown Work

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
Need to skip internal SATA Disk configured as in AHCI Mode. These disks has to be used for OS installation or left as-is
=> ASM-6387 ASM to support Urgent Fury vSAN RA

bin/discovery.rb, bin/esx_software_discovery.rb
This is first task for gathering VIB inventory for a ESXi host via a new script esx_software_discovery.rb
With relevant PUT device/:cert_name API in asm-deployer, this script will be invoked.
The fields from the inventory for each VIB package include:
AcceptanceLevel, CreationDate, ID, InstallDate, Name, Vendor, Version
=> ASM-6570 Task : script in vcenter module to gather ESX software inventory

bin/esx_software_discovery.rb
Seems esxcli software vib list does not accurately indicate the VIBs, especially when VIBs are removed.
The new method of using esxcli software vib get is more trustworthy.
=> ASM-6570: Use reliable method to get all VIBs, with more details

lib/puppet/provider/esx_advanced_options/default.rb
Additional parameters added for VSAN configuation do not have optionType leading to NillClass error. For parameters where we don't have type. we are using it as integer class which is default type
=> ASM-6707 VSAN settings to support H730 controller

lib/puppet/provider/esx_software_update/default.rb, lib/puppet/provider/vcenter.rb, lib/puppet/type/esx_software_update.rb, lib/puppet_x/puppetlabs/transport/vsphere.rb
Puppet type and provider for ESXi VIB updates
=> ASM-6588: Apply the vib update on ESXi host

bin/discovery.rb, bin/esx_software_discovery.rb
To support server and chassis discovery scripts to accept credential_id as parameter, ASM deployer's run_script will pass credential_id as command line arguments to any discovery scripts (similar to passing other generic arguments like username,password,output,community)string).
This means Trollop of the discovery scripts needs to declare accepting credential_id param, even if it is no-op.
=> ASM-6521, ASM-6522 Make discovery scripts recognize credential_id

bin/discovery.rb
collect_vds_portgroup_attributes inspected the
`defaultPortConfig.vlan` for a vlanId but in some cases it is passed a
`VmwareDistributedVirtualSwitchPvlanSpec` that does not have that
method.
Example data:
[1] pry(main)> portgroup.config.defaultPortConfig.vlan
=> VmwareDistributedVirtualSwitchPvlanSpec(
dynamicProperty: [],
inherited: false,
pvlanId: 20
)
=> ASM-6833 vCenter discovery can fail for pvlanId inventory

lib/puppet/provider/vc_vm/default.rb
The behavior before was to leave the first adapters and "shift" the
networks down on to those adapters by editing the network on them. Now
we are just eliminating the adapters for the networks no longer needed.
Solves an issue where we apply a static network IP on the 2nd adapter,
but then we wipe out that 2nd adapter, making us lose that config as
well as leaving our VM without network connectivity in some cases.
=> Change to vm to remove adapters for networks no longer needed

lib/puppet/provider/vc_storagepod/default.rb, lib/puppet/provider/vc_vm/default.rb, lib/puppet/type/vc_storagepod.rb
* Add param for Storage DRS enablement to storagePod resource.  
* Add ability to create VM on storage cluster.  
* If no datastore is explicitly supplied, the ordering will use Storage Pod -> Remote Datastore -> Local Datastore (each ordered by available space) for choosing which datastore to deploy the VM to
=> ASM-2266 Storage Cluster with DRS and VM deployment

bin/esx_software_discovery.rb, lib/puppet/provider/esx_software_update/default.rb, lib/puppet_x/puppetlabs/transport/rbvmomi_patch.rb, lib/puppet_x/puppetlabs/transport/vsphere.rb
Seems with ESX 6.0, VMware added some APIs which do not have the returnTypeInfo defined in VMODL:
e.g. WitnessJoinVsanCluster, WitnessSetPreferredFaultDomain, AddUnicastAgentWitness, LeaveVsanCluster, RemoveUnicastAgent
The EsxCliNamespace used by the host object in ESX discovery and software updates ends up invoking RbVmomi::VIM::DynamicTypeMgrManagedTypeInfo.toRbvmomiTypeHash, where it tries to access properties of returnTypeInfo of every VMODL APIs.
As a result, when it encounters any of above mentioned methods, it results into NoMethodError.
To workaround such problem, we monkey-patch the toRbvmomiTypeHash by setting result = nil for such methods without any returnTypeInfo.
=> ASM-6587 Workaround NoMethodError in toRbvmomiTypeHash method in rbvmomi

lib/puppet/provider/vc_spbm/default.rb, lib/puppet/provider/vc_vsan_disk_initialize/default.rb, lib/puppet/type/vc_vsan_disk_initialize.rb
Instead of finding the type of disk-group type based on the NIC, used the user specified value to ensure disk-group type is aligned with ASM user input
=> ASM-6603 Support vSAN read Nodes with FX2 All-flash platforms

lib/puppet/provider/vc_vsan_disk_initialize/default.rb, lib/puppet/type/vc_vsan_disk_initialize.rb
As per the story, we need to redirect VSAN traces to external datastore.
In the puppet module, we are passed a volume name to set for all hosts,
and we simply apply that.
The business logic of determining the right volume name is done in
asm-deployer. We set vsan traces to this datastore corresponding to this
volume name using the relevant esxcli API
=> ASM-6600 [puppet] Redirect vSAN traces to an external datastore

lib/puppet/provider/esx_software_update/default.rb
This is to avoid misconception that all VIBs update were successful if we don't there were some or no VIBs updated
=> ASM-7104 Raise error for software update if there were some or no VIBs failed to install

lib/puppet/provider/vc_vm/default.rb, lib/puppet/type/vc_vm.rb
Allow a `virtual_disks` param to be used which contains a list of
disks and their sizes. *order matters*  If the param is used, multiple
storage devices will be created for the virtual machine
=> ASM-2675 Multi VirtualDisk configuration for VM

bin/discovery.rb
Skip discovery of VSAN Profile Management policy facts listing for vCenter 5.1 as this is not supported for 5.1
=> ASM-7251 Unable to discover vCenter 5.1

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
If disk initialization is skipped, we were not calling set_vsan_trace method.
The fix is to simply invoke the method irrespective of calling the vsan disk init or not.
=> ASM-7320 Set VSAN traces if disk init is skipped

bin/discovery.rb, lib/puppet/provider/vc_spbm/default.rb, lib/puppet/provider/vc_vm/default.rb
- Instead of just passing the name, we have to pass profile identification to work consistently.
- Discovery of storage profile was getting skipped with vcenter version 5.5
=> ASM-7315 VSAN vm's are not getting associated with the ASM storage policy

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
Setting VSAN traces before disk configuration worked fine. However, it
leads to problem later when we check if the disks are configured.
To workaround this problem, we set VSAN traces later in disk init process.
=> ASM-7320 Defer setting VSAN traces for a host after disk configuration

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
It seems, when datastore url starts with ds:/, vsan traces set does not work
for all cases.  Instead trimming down the url to start with // path works.
Hence, we remove ds:/ reference from the url and then set the trace.
=> ASM-7404 Set VSAN traces for compellent datastores

lib/puppet/provider/vc_spbm/default.rb
Debug message was using old resource parameter leading to the failure when failure tolerance method name is different from what is already configured in the policy
=> ASM-7443 VSAN deployment with RAID 5 fails

lib/puppet/provider/vc_vm/default.rb
For Virtual disk associated with VSAN enabled cluter was not associated with ASM specific storage policy. Update the storage policy to be associated with VM and HDD specifically
=> ASM-7475 VSAN Storage policy not attached to VMware Virtual Disk

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
Skipped local disk from eligible disk for creating the VSAN disk-group. These are just spare disk added as part of BOM and are not expected to be added to VSAN disk-group
=> ASM-7519 Backplane disk is added to the VSAN disk-group for R730XD servers

lib/puppet/provider/vc_spbm/default.rb, lib/puppet/type/vc_spbm.rb
We were not removing a rules which takes care fault tolerance method. Default value of the rules is set to "none". In case value is not specified from the asm-deployer, we will remove the rule which takes care of fault tolerance method.
=> ASM-7541 ASM default storage policy not overwritten when switched from All flash to Hybrid deployemnts

lib/puppet/provider/esx_software_update/default.rb
Seems there are cases where host reboot may take longer than
anticipated. We need to add information in logs to know how long
it took to connect for debugging purpose. Also we add a log entry if
we find the host reboot timeout happened and we were still not able
to have connected host.
=> Add timing information when rebooting host during VIB updates

lib/puppet/provider/vc_spbm/default.rb
Updated default vale of fault tolerance method name from "nil" to "none". Now while creating new storage policy if the value if not provided then skip the fault tolerance method
=> ASM-7637 Storage policy create operation is failing for Hybrid VSAN configuration

lib/puppet/provider/vc_vsan_health_performance/default.rb, lib/puppet/type/vc_vsan_health_performance.rb, tests/vc_vsan_health_performance.pp
Added support for enabling / disabling VSAN health performance services. By default health services is not enabled when VSAN is enabled on the cluster and due to this, a warning message is shown in VSAN health table
=> ASM-7640 Warning Messages thrown in FC 630 cluster for VSAN

lib/puppet/provider/esx_alarm/default.rb
Instead of using API FindByIP we need to use FindByDnsName so that we can support both IP and Hostname deployments
=> ASM-7728 ESXi deployment with FQDD hostname is failing while clearing alarms

lib/puppet/provider/vc_vm/default.rb
For clone operation datatore name is not passed for relocation spec passed to VM clone operation. These changes seems to be got broken due some recent changes while adding virtual disk support.
=> ASM-7729 VM clone operation fails when performed across cluster or datacenter with no common datastore

bin/esx_software_discovery.rb
Fetching ESX software components is a quick operation, requiring on an
average of 3 seconds. We reduce the timeout from 240 seconds to 20 seconds
so that servers that have ESX not responding can timeout quicker instead
of looping for long time causing UI timeout wierd issues.
However, this is a short term solution. We noticed that even with 20
second timeout in this script, the expected failure seen by the endpoint
is close to 60 seconds. We need to root cause of this extra latency seen
in asm-deployer.
=> ASM-7754 Reduce timeout on ESX software discovery

lib/puppet/provider/esx_connection_wait/default.rb, lib/puppet/provider/esx_software_update/default.rb, lib/puppet/provider/vcenter.rb, lib/puppet/type/esx_connection_wait.rb, tests/esx_connection_wait.pp
Move the logic of waiting for host into a utility function in vcenter.rb
so that it can be used by all vmware puppet resources.
We also create a new resource esx_connection_wait that can be used after
kicking of ESX reboot on firmware updates
=>  ASM-7569 Move wait for host connection logic out into a seperate resource

lib/puppet_x/puppetlabs/transport/vsphere.rb
When we connect a host first time through vsphere transport, the @options
contain only minimal connection params. Once a connection has been
established, @options gets populated with metadata such as ns, ssl,etc.
On reconnecting a host(in case of reboot scenarios ), these extra
metadata creates a VIM connection that fails for esxcli API operations
with error "Not supported with VC less than 5.0" which seems like a bug
in vSphere web services. We fix this issue in reconnect by creating a
VIM connection with the minimal connection params.
=> ASM-7760 Fix VIM API issues with esxcli on reconnected host

lib/puppet/provider/esx_maintmode/default.rb, lib/puppet/provider/esx_software_update/default.rb
Seems if we do not have this flag, VSAN hosts can fail to enter maintenance
mode because in absence of VSAN action not supplied then VSAN datastore
integrity and accessibility test takes a lot of time and leads to timeout.
If host is not a VSAN host, this flag will not impact maintenance mode.
=> ASM-7861  Ensure no VSAN action for maintenance mode during server updates

lib/puppet/provider/esx_reconfigureha/default.rb
previously Ha-reconfigure was not running if the connection state is master or connected to master even if it has warning message.
With this PR we also check the config status of the host, if it has any issues and re configures_ha
=> ASM-7886:reconfigure_HA when warninng message even on master connection state

lib/puppet/provider/vc_vsan/default.rb
As recommended by VMware team, we have included flag "allowreducedredundancy" for the VSAN cluster while enabling de-duplication. This will help in enabling / disabling redundancy while lesser number of nodes in the VSAN cluster
=> ASM-8110 Enabled "reduced redundancy" for VSAN cluster while invoking de-duplication for VSAN cluster

bin/discovery.rb
Multiple instances have been observed recently with vCenter 6.0 where storage profile retrieval is failing due to unknown reasons. Support request is sent to VMware team to provide the root case for the same. Rescue block is added to get discovery going will we get the resolution / root cause of the problem
=> ASM-8111 vCenter inventory fails due to problems getting storage profiles

lib/puppet/provider/vc_dvswitch/default.rb
Previously ASM was unable to set lldp protocol, used to be cdp by default
This PR will enable lldp protocol while creating vds. It will always set
to lldp, instead of getting as resource parameter it is directly set in
vcenter pupppt module.
=> ASM-7925: Enables lldp on vds in vcenter cluster

bin/discovery.rb
In scenarios with large vCenters (~30 hosts, 1k+ VMs) the discovery
script is seen to take about 10 minutes. This changes simply bumps the
default timeout up from 4 minutes to 15 minutes to account for
that. In the future we may want to see if we can improve the speed of
discovery perhaps by inventorying less data on individual hosts.
=> ASM-8072 Increase vcenter discovery timeout to 15 minutes

bin/discovery.rb
Adding server's maintenance mode addtibute for each server inventories by ASM. This will help in deciding if server's firmware update needs to be invoked
=> ASM-8057 ASM is not reporting failure when depl fails to exit maintenance mode

bin/discovery.rb
Brownfield discovery were not getting service tag fields if invoked via
`host.esxcli.hardware.platform.get.SerialNumber.` The root cause is that 6.0
onwards the SOAP responses from esxcli are not missing return types for some
methods in rbvmomi gem we have. This creates errors like below:
```
NoMethodError: undefined method `name' for nil:NilClass
from /opt/puppet/lib/ruby/gems/1.9.1/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/DynamicTypeMgrManagedTypeInfo.rb:33:in `block in toRbvmomiTypeHash'
```
We had seen same thing in esx_software_discovery script in the past and
had introduced a rbvmom_patch to resolve the missing return type issue. We
use this same patch after including rbvmomi gem to resolve the issue.
=> ASM-8218 Fix NoMethodError in rbvmomi lib in vcenter discovery

lib/puppet/provider/esx_maintmode/default.rb, lib/puppet/type/esx_maintmode.rb
For some use cases, we may not want the maintenance mode resource exists
to fail if host is not available or maintenance mode state cannot be
determined. In such case, we provide a flag to prevent failure in exists?
and prevent unwanted invocation of create/destroy
=> ASM-8331 Flag to not fail when maintenance mode state cannot be determined

lib/puppet/provider/vc_vsan_network/default.rb
In case of multiple port-groups code was failing for normal port-groups as it was anticipating an array in the resource hash.
=> ASM-8426 VSAN Deployment failing with VSS networking while configuring VSAN Network

lib/puppet/provider/vc_vsan_health_performance/default.rb
Included error handling for the scenario where intermittently existing method returns the status of health services as not configrued and while enabling the services getting "FlieAlreadyExists" error message
=> ASM-8428 Intermittent error is observerd while enabling VSAN health and performance services

lib/puppet/provider/vc_vsan_network/default.rb
In case there is a one VSAN network cluster, and a scaleup is performed with a server with two VSAN network an empty distributed port-group name is resource file leading to a null error.
=> ASM-8468 R730XD Deployment failed after server scale up having 2 vsan vlans

lib/puppet/provider/esx_software_update/default.rb
For consistency, we use exception object represented by $! which is still
the same exception rescued.
=> Misc: some consistent use of $!

bin/esx_software_discovery.rb
For brownfield services, there is no option of ESX credentials. Here we
provide capability to make use of VC credentials to fetch necessary ESX
software inventory. Also took care of some styling changes.
=> ASM-8558 Use VC credentials to fetch ESX software inventory

lib/puppet/provider/vc_dvswitch/default.rb
While retrying the VSAN teardown if the resource is already removed in the previous atttempt then cleanup operation fails with error "Item could not be found". We need to ignore this error and continue with the cleanup operation
=> ASM-8666 vSAN tear down does not remove the cluster and host from vCenter

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
Added debug messages for VSAN disk selection so that we can collect the scenario where disks are skipped from the disk-group creation process.
Also, included a retry mechanism where free disks are identified after disk-group creation process is completed. If a free eligible disk(s) is identified which is not included in the existing disk-group then same will be added to the disk-groups
This code flow will also take care of the scenario where a new disk is added to the server after initial disk-group creation process. The newly added disk will included in the disk-group when retry of the service is initiated.
=> ASM-8580 Some vSAN deployments do not attach all the available disks to the cluster

bin/discovery.rb
we have included all standard and distributed port groups available on each of the server. This new information is added at the same level as VM and datastore. Here Type will be “DistributedVirtualPortgroup” or Network. VLAN ID is available as an attribute to it.
Example
{"name"=>"iscsi1",
"id"=>"dvportgroup-696",
"type"=>"DistributedVirtualPortgroup",
"attributes"=>{"vlan_id"=>16},
"children"=>[]},
=> ASM-8215 Update behavior and fix issues for VDS network scale up.

bin/esx_software_discovery.rb
It is possible that host DNS-name may be passed as host_ip. In that case
we try out different VIM API.
=> ASM-8604 Support DNS host name for host-ip during ESX software inventory

lib/puppet/provider/vc_vm/default.rb
Previously existing ide controller 200 for(0:0) on vm cd failes
to install os on first disk.
This PR will change cd_drive controller id to install os on first available disk.
=> ASM-8648 Changed cd/Dvd drive ide controller id

lib/puppet/provider/vc_vm/default.rb, lib/puppet/type/vc_vm.rb
Asm has no support for mounting iso.It creates empty
cd drive while creating VM.
This PR adds cd device config as parameters and runs puppet
to mount iso file by adding NFS datastore. It unmounts iso and
NFS after completing a specified task. multiple NFS datastore
may be attached on a host with VM specific name.
=> ASM-8811 Mounts ISO to CD/DVD drive for vm

lib/puppet/provider/vc_vm/default.rb
Previously ASM used to consider only first cluster domain to find the vm_host. This Pr will check for the host from multiple cluster domains
=> ASM-9312 Resolved getting vm_host on multiple cluster domains

bin/discovery.rb
Included VLAN information for standard port-group which was missing in the existing inventory for vCenter.
=> ASM-9315 Network scale-up only shows a single used network - missing all the other available networks

bin/discovery.rb
The previous fix for ASM-9481 missed scenario where the networkInfo can also be
nil, causing undefined method `portgroup' for nil:NilClass.
=> ASM-9481: Fix nil class exception when networkInfo is nil

lib/puppet/provider/vc_vm/default.rb
Previously ASM use to cache the vm object returned by findvm method. This prevents
source vm_obj being overridden with new created vm object in clone scenarios.
This PR will not cache the vm object returned by findvm.
=> ASM-9516 removed using cached vm object

bin/discovery.rb, lib/puppet/provider/vc_migratevm/default.rb, lib/puppet/type/vc_migratevm.rb, tests/vc_migratevm.pp
In case empty datastore name is passed then we check for all available datastore having sufficient disk space for hosting the Virtual Machine.
Include datastore name in the discovery data of Virtual machine. This helps in identifying VMs hosted on a specific datastore.
=> ASM-9568 scaledown vol is not migrating vms to another vol

lib/puppet/provider/vc_migratevm/default.rb
Debug message added for listing the selected datastore was not in correct sprintf format, leading to the syntax error.
=> ASM-9650 VM Datastore migration failing for SDRS based storage

lib/puppet/provider/vc_vm/default.rb
Previously clone vms always powersOn after creating vm.
with the recent changes to mount iso for configuring static network,
powering_on vm without mounting iso may cause issues.
This PR will make sure the vm is poweredOFf. Later, other puppet run by
asm-deployer will powerOn the vm after mounting iso on cdDrive.
=> ASM-9004 Avoids Clone vm powerON to get vm networks

lib/puppet/provider/vc_migratevm/default.rb
There is a typo in the debug message which prints the name of the datastore selected for the migration. This statement was updated as part of the code review and a typo got introduced there
=> ASM-9693 VM MIgration failed during scale-down of the datastore

bin/discovery.rb
In 8.3.1 the timeout was increased from 4 minutes to 15 minutes. The
script was timing out against some vcenters with large inventory
including remote ESXi hosts. Recently the same vcenter was seen to
take 24 minutes to inventory so it was still timing out. For now
bumping the timeout up to 1 hour to cover that case. At some point we
need to find some way to optimize this.
=> ASM-8072 Increase vcenter inventory timeout to 1 hour

lib/puppet/provider/vc_vm/default.rb
While passing the specific datastore name for VM creation, operation was failing in the debug message.
Also in the return statement we were just sending the name of the datastore (old convention) but with the new code structure, datastore object information was required.
Validated the code for VM creation on specific host in the cluster.
=> LUD-204 Create ScaleiO CentOS VM on specific host / datastore in the cluster

manifests/package.pp, metadata.json
Allow for the gem_provider to be overridden by class definition or hiera. Enables support for Puppet 4 which has depreciated pe_gem in favor of built in puppet_gem provider. See https://github.com/puppetlabs/puppetlabs-pe_gem
Added metadata.json to allow for installation of dependencies with puppet module install command or forge.
=> Gem provider

Gemfile, lib/puppet/provider/esx_datastore/default.rb, lib/puppet/provider/vc_vm/default.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
LUD-224 Do not pick NFS share for VM deployment
An NFS datastore is used to mount ISO images, i.e. to boot a VM off of
an ISO image. Those datastores were getting picked for VM deployment
on ESXi hosts that only had local datastores. That is because they are
interpreted as "remote datastores" which are prioritized above local
datastores.
Also adds some general unit testing aroung the related
`get_cluster_datastore` functionality.
=> LUD-224 Do not pick NFS share for VM deployment

lib/puppet/provider/esx_portgroup/default.rb, lib/puppet/provider/vc_dvportgroup/default.rb, lib/puppet/provider/vc_dvswitch/default.rb, lib/puppet/type/esx_portgroup.rb
This PR supports nic teaming policy for vswitch and dvswitch.
=> LUD-38 NIC teaming mode to support Hypervisor deployment

lib/puppet/provider/esx_pci_passthru_system/default.rb
Host needs to be put in maintenance mode prior to rebooting.
=> LUD-37 Reboot fix for `esx_pci_passthru_system`

bin/discovery.rb
Fixed inventory failure caused by nil class on host.summary.hardware info not being populated.
=> LUD-742 Deployment failed due to vcenter inventory failure

bin/discovery.rb
Skip discovery of vCenter host for which `config` object is Nil. Observed this error in BDC deployment where discovery failed while collecting the network configuration informtion when host.config object was Nil
=> LUD-1070 vCenter discovery failure with disconnected host

bin/discovery.rb
Included configuration version of the distributed port-group in the inventory facts. Config Version 10 is for the uplink distributed port-group.
=> LUD-1188 Deployment into existing VDS fails if uplinks renamed

lib/puppet/provider/vc_vm/default.rb
Instead of having x number of CPUs as individual sockets, this change
puts all cores into one socket.
=> LUD-1220 change VM CPU cores/socket configuration

lib/puppet/provider/vc_vm/default.rb
Initially, the jira issue describes the problem for VDS name with
spaces only. However, tests show that distributed portgroups names
can also cause failure.
At first, the solution was to be implemented on the asm-deployer,
but handling different types of backing data for network device
configuration still seemed to have other issues. After tracking the
root cause, the issue has been found in the regex, used for parsing
portgroup / vds names.
The old regex only works with interface name that contains no space
in both portgroup and vds names, e.g., "portgroup_name (vds_name)".
This new regex is able to handle the old case as well as names
that contain space(s). Now the names can be passed with a single
or multiple spaces, e.g., "portgroup name (vds name)" and
"pg 1 test (test vds 1234)".
=> LUD-1216 allow spaces in VDS and portgroup names

bin/discovery.rb
Including VDS uplink information in discovery facts. This data will be used while creating the uplink information for an existingt VDS switch configuration. Change in the name and count of the VDS is not allowed by vCenter
=> LUD-1484 Failure to add to existing VDS ('Uplink 1' in use)

lib/puppet/provider/vc_vm_pci_passthru/default.rb, lib/puppet/type/vc_vm_pci_passthru.rb, tests/vc_vm_pci_passthru.pp
Added new resource for Virtual Machine PCI device configruation. In case VM is missing PCI device configuration or there is a mis-match in the PCI device ID mapping then this resource will take of server reconfiguration
=> LUD-1448 PCI pass-through settings lost during HBA330 firmware downgrade

lib/puppet/provider/esx_vmknic/default.rb, lib/puppet/provider/vc_cluster_ha/default.rb, lib/puppet/provider/vc_dvportgroup/default.rb, lib/puppet/provider/vc_dvswitch/default.rb, lib/puppet/provider/vc_vm/default.rb
Several debugging statements in the vcenter puppet code were dumping
huge (10-27MB per line) object data thereby creating very large
log files. This fix deletes the offending debug statements as they
were deemed unnecessary.
=> VXFM-1662 Puppet logs are ludicrously large

lib/puppet/provider/esx_pci_passthru_system/default.rb, lib/puppet/type/esx_pci_passthru_system.rb
To allow the server configuration in server swimlane, provider
and type for esx_pci_passthru_system resource are modified.
Now reboot is requested after configuring the target PCI device
only when require_reboot is true. Also, reboot method will no
longer enter and exit maintenance mode. Instead, this type of
tasks should be defined in the puppet resource through dependencies
on esx_maintmode resource.
=> VXFM-2342 changes for configuring PCI device in server swimlane

bin/discovery.rb
Discovery operation takes around 6-7 seconds to complete. But if the server is in disconnected state, then it takes around 2-3 minutes. Changes will skip discovering VIB facts for servers in disconnected state.
=> VXFM-2880 discovery script is taking way too long to complete during deployment

lib/puppet/provider/esx_maintmode/default.rb, lib/puppet/type/esx_maintmode.rb
Skip maintenace mode operation while removing the server from maintenance mode if server is in disconnected state
=> VXFM-3109 Scale-down not removing node from cluster

lib/puppet/provider/esx_pci_passthru_system/default.rb
Checking the pci passthru device status at the end of change will
break when the reboot is required. Since puppet already calls
exists? method to determine the status at the end, it is now
removed.
=> VXFM-1448 remove obsolete checks that breaks the puppet run

lib/puppet/provider/esx_datastore/default.rb, lib/puppet/type/esx_datastore.rb
Included parameter disk model and disk id for searching the disk that needs to be mapped and mounted as a datastore. In case there are multile local disks, then all of them becomes cadidate to be mounted as the datastore. Now we we will check for model, target id and lun id before mounting the volume as a datastore
=> VXFM-3435 Wrong disk mapped on CO deployment

lib/puppet/provider/vc_vm_pci_passthru/default.rb
Fixed issue where we could not find vmware vm for SVM when the vm
happened to be buried in a folder.
=> VXFM-3794 Unable to exit service mode in the VAST system BF service.

lib/puppet/provider/esx_vmknic_type/default.rb
Intermittently VMK NIC Type update to vMotion is failing when distributed switch and port-group is created on the switch. Added sleep and retry for this process to ensure distributed port-group is in a stable state when new server is added to the distributed port-group
=> VXFM-3944 VMK NIC Type update is failing for vMotion distributed port-group for new port-group

lib/puppet/provider/esx_vmknic/default.rb
VMNIC needs to be attached to a specific port on VDS switch. Intermittently port is already used and correct ID is not determined. Need to wait and re-created the configuration in case of failure.
=> VXFM-3187 VMNIC configuration fails intermittently while finding dvs switch uuid

bin/discovery.rb
Discovery operation fails while fetching the datastore information of the VM. For Orphan VMs, datastore information is missing from the vCenter MOB. We are skipping the datastore information from the discovery data in case there is not datastore attached to the virtual machine.
=> VXFM-3911 Discovery of vCenter fails when orphan VMs are available on vCenter

lib/puppet/provider/vc_dvswitch/default.rb
For ESXi 6.7 we need to pass VDS version as 6.6.0. This is a one of case required for this version
=> VXFM-4346 VDS creation is failing for vCenter 6.7

lib/puppet/provider/esx_software_update/default.rb, lib/puppet/type/esx_software_update.rb
Added support for installation of unsigned VIBs by ignoring the VIB signature. In case the flag is passed, then VIB without signature will be installed. Default behavior still remains the same where unsigned VIB will not be installed
=> VXFM-4321 ESXi 6.0 VIB is missing signature

lib/puppet/provider/esx_datastore/default.rb, spec/unit/puppet/provider/esx_datastore/esx_datastore_spec.rb
Add code to see if selected disk alread has a VMFS filesystem. This is detected by determining if VmfsDatastoreCreateOptions data notes that a format change is required.  For existing datastores, a reformat will not be necessary.
=> VXFM-4390 Mapping CO volume may recreate VMFS due to different LUN numbers

lib/puppet/provider/esx_datastore/default.rb, spec/unit/puppet/provider/esx_datastore/esx_datastore_spec.rb
numbers
Add code to see if selected disk alread has a VMFS filesystem. This is
detected by determining if VmfsDatastoreCreateOptions data notes that
a format change is required.  For existing datastores, a reformat will
not be necessary.
=> VXFM-4390 Mapping CO volume may recreate VMFS due to different LUN

bin/discovery.rb
Recent change for VXFM-5314 broke discovery if the vcenter had folders
instead of just datacenters.
=> VXFM-5314 Fix discovery for vcenters with folders

manifests/host.pp
Enabled SSH on all ESXi servers in the cluster which is required by the VxOS gateway to collect the logs for the SDC communication.
=> VXFM-6023 Log collection fails with VxFM-deployed VxFlex OS cluster

lib/puppet/provider/vc_vm/default.rb, lib/puppet/type/vc_vm.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
validation check was looking for the existence of flag `enable_nvdimm` in the resources. This flag is passed in all the cases with value as `false`. We need to perform the operation only when the value of the flag is `true`
=> VXFM-6963 Skip NVDIMM configuration where NVDIMMs are missing on the server

bin/discovery.rb
In case a folder is created on top of a datacenter then port-goup information is empty that object. We need to skip the objects which are empty
=> VXFM-7798 vCenter fails to inventory due to missing portgroup_data

bin/discovery.rb
Create collection of port-group and datastore like distributed port group before retreiving information for each of the server. Instead of getting the datastore information for each of the server, we are collecting the information of the datastore before hand
=> VXFM-7666 Continue improving vcenter inventory script time

lib/puppet/provider/vc_vm/default.rb
Modified code to accept parenthesis in Distributed Virtual Port group settings
=> VXFM-8788: Using parenthesis in Distributed Virtual Port group settings that get applied to VMs fail

lib/puppet/provider/vc_dvswitch_migrate/default.rb
Missed removing one of the hard coded lag names.
=> VXFM-9335 LACP lag configuration needs to handle existing VDS switch LAGS

lib/puppet/provider/vc_vm/default.rb
Create VM operation failing while setting the network interface info. This is a regression for the recent changes added for create VM for supporting CLC VM creation
=> VXFM-10630 Create VM operation failing for Gateway VM creation

lib/puppet/provider/esx_datastore/default.rb
Disk model name is reported as "VxFlex-OS" instead of "ScaleIO" with VxOS 3.5. Adding support for fetching both the disk types
=> VXFM-10877 Add Vol failing for HC service - FlexOS GW 3.5-0.393
