lib/puppet/provider/esx_iscsi_options/default.rb, lib/puppet/type/esx_iscsi_options.rb
Added a new resource for updating iSCSI adapter parameters required for iSCSI communication
=> ASM-2227 2228 2229 EqualLogic performance parameter

lib/puppet/provider/esx_reconfigureha/default.rb, lib/puppet/type/esx_reconfigureha.rb, tests/esx_reconfigureha.pp
Added new resource for initiating the reconfigure ha agent on the ESXi host. Its been observed that after loosing the network connectivity HA agent looses connection to the HA Master
=> ASM-2870 When scaling up an ESXi HA cluster, the additional host has error

lib/puppet/type/esx_reconfigureha.rb
https://docs.puppetlabs.com/guides/custom_types.html#boolean-parameters
=> ASM-3834 Require Puppet::Parmater::Boolean

lib/puppet/provider/vc_vm/default.rb
Sort the datastores so that we prefer the remote datastore with most
free space and fall back to local datastore with most free space.
=> ASM-4631 prefer remote datastores with most free space

lib/puppet/provider/vc_cluster_evc/default.rb
Simply print out the current EVC mode/status
=> ASM-4678 Don't block if EVC configured

lib/puppet/provider/vc_dvswitch/default.rb, manifests/dvportgroup.pp
- Updated manifest file to include transport parameters
- Updated vc_dvswitch resource for error handling in case a existing host is re-added to the VDS
=> ASM-4855 I want to be able to create my iSCSI vSwitch as VDS for EQL

bin/discovery.rb
SHould be merged with: https://github.com/dell-asm/asm-core/pull/1929
So far it only has the basic information that we currently have, along with the service tag for servers.  Storage information was giving me problems, so I just pushed what I have (which is just everything that we had before mostly).
=> ASM-4858 added vcenter inventory script

lib/puppet/provider/vc_dvswitch/default.rb, lib/puppet/type/vc_dvswitch.rb, manifests/dvswitch.pp
- Allow creating VDS with specific version
- Enabled search of host based on the VDS version
=> ASM-5077 Allow VDS to be created according to host versions

bin/discovery.rb
I recommend reviewing this without the whitespace
=> ASM-5125 ASM-4859 Service tag and nfs datastore additions

lib/puppet/provider/esx_alarm/default.rb, lib/puppet/type/esx_alarm.rb, tests/esx_alarm.pp
Adding support for clearing the alarms from the ESXi host.
=> ASM-5508 ESXi iSCSI compellent deployment is having host in vcenter with alarm

bin/discovery.rb
=> Added NFS volume path for NFS datastores

lib/puppet/provider/vc_vsan/default.rb, lib/puppet/type/vc_vsan.rb, tests/vc_vsan.pp
- Added resource to manage VSAN and auto-claim feature for ESXi cluster.
=> ASM-5562 vCenter Puppet module changes for Phase 1 vSAN support for RA HCL

lib/puppet/provider/vc_vsan/default.rb, lib/puppet/provider/vc_vsan_disk_initialize/default.rb, lib/puppet/type/vc_vsan_disk_initialize.rb
Enable disk-group deletion of servers added to the VSAN enabled cluster.
=> ASM-5858 VSAN Teardown Work

lib/puppet/provider/esx_maintmode/default.rb, lib/puppet/type/esx_maintmode.rb
@gavin-scott would you review and merge to master branch?
=> Branch merge 820 to master vmware vcenter 40

lib/puppet/provider/vc_vsan_disk_initialize/default.rb
@jkrauskopf John, this is another froward pull request from 820 to 830. Please review. Thx.
=> Branch merge 820 to master vmware vcenter 56

lib/puppet/provider/vc_vm/default.rb
There was a lot of incorrect behavior with the code that shifted the networks.
It was leaving extra network adapters, it would not work if there was the name
number of networks on the VM as we're trying to set (even if we're trying to
set different networks). This code should help make the behavior more correct
overall and should help solve standing issues with network scale up
=> ASM-6373 Refactored network_interfaces setting code

lib/puppet/provider/vc_vm/default.rb, lib/puppet/provider/vc_vsan_disk_initialize/default.rb
@gavin-scott Please review and merge
=> Branch merge 820 to master vmware vcenter 79

bin/discovery.rb
@gavin-scott see if you want to forward merge this one?
=> Branch merge 820 to master vmware vcenter 110

lib/puppet/provider/spbmapiutils.rb, lib/puppet/provider/vc_spbm/default.rb, lib/puppet/provider/vc_vsan/default.rb, lib/puppet/provider/vc_vsan_disk_initialize/default.rb, lib/puppet/provider/vsanapiutils.rb, lib/puppet/type/vc_spbm.rb, lib/puppet/type/vc_vsan.rb, tests/vc_spbm.pp
In case there is only SSD disk on the server, then we will create AllFlsh type of DiskGroup else Hybrid DiskGroup will be created.
=> ASM-6603 Support vSAN read Nodes with FX2 All-flash platforms

lib/puppet/provider/vc_vm/default.rb
@gavin-scott Gavin, see if you want this PR merged. Lots of changes.
=> Branch merge 820 to master vmware vcenter 61

bin/discovery.rb, lib/puppet/provider/vc_spbm/default.rb, lib/puppet/provider/vc_vm/default.rb, lib/puppet/provider/vc_vsan_disk_initialize/default.rb, lib/puppet/type/vc_spbm.rb, lib/puppet/type/vc_vm.rb
Added support for creating storage policy creation and associating same with VM creation if provided as input
=> ASM-7031 Always create an ASM storage policy and later can be used for VM deployment

lib/puppet/provider/esx_software_update/default.rb
Add few more logs to the puppet module of some of the steps to help troubleshoot issues.
Also in exists? method raise an error when there is any exception.
=> ASM-6923 Software VIB updates logging

lib/puppet/provider/esx_software_update/default.rb
Found out that if there are invalid VIB binaries sent, we can end up in
an 'NilClass' exception from rbvmomi when installing the VIB. Instead of
stopping at error vib, we want to install as many VIBs as possible, and
log any failures.
In the end we altready have logic to fail the update if count of installed
VIBs does not equal count of "to install" VIBs.
Note: Also we change Puppet.error to Puppet.err since Puppet.error is not
defined.  Perhaps we should have rubocop to catch this.
=> Attempt to install as many VIBs as possible

lib/puppet/provider/esx_software_update/default.rb
After initiating reboot request to host, we used to wait for 3 minutes
before checking conneciton status, to allow sufficient time for host to
prepare for reboot and reflect correct connection state. However, it seems
in QA environment, this prep may sometimes take more than 3 minutes giving
us false impression of host is connected, and later fails to do other host
operations like entering MM, when the host is in process of rebooting.
For short term fix, we increase the initial sleep from 3 minutes to 5
minutes. We plan to address this timeout thing and host connection
reliable state in later release.
=> ASM-7567  Change initial sleep to 5 minutes after kicking off host reboot

lib/puppet/provider/esx_software_update/default.rb
For software updates on VIBs, if some of the VIBs are not installed, then
we may end up scheduling NFS unmount after rebooting the ESX host which
seems to not work.  We can see strange error message due to this:
RuntimeError:esxcli not supported through VC before 5.0.0
The fix is to unmount before reboot operation.
Also in this PR, we remove the unnecessary begin/rescue for entire
install operation, which is only need for install_vib.
=> ASM-7676 Failed to unmount NFS share after rebooting host

lib/puppet/provider/vc_vsan_health_performance/default.rb
Addressing the code comments which were added to the merged code. Added exception handling block for teardown.
=> ASM-7640 Warning Messages thrown in FC 630 cluster for VSAN

lib/puppet/provider/esx_software_update/default.rb, lib/puppet/type/esx_software_update.rb
The esxcli API to install vibs already supports passing an offline bundle
which is essentially a ZIP with vibs. All dependent VIBs are part of this
bundle and seems to work if installed as single batch.
In addition to above changes, we also do a peformance optimization to not
query a source VIB for vib_id as it is already passed via instance_id to
this puppet module.
Also did a minor refactor to move some of the pieces in exists? method
into its own methods.
=> ASM-7658 Support installing VIBs in a zip for use cases with dependencies

lib/puppet/provider/esx_software_update/default.rb
Background of the problem:
Sometimes, if there is a pre-exisiting firmware updates before a software
update, after rebooting the host may lose its maintenance mode state.
This can cause issue "Cannot perform the operation in current state"
on invoking wait_for_completion on a reboot action on the host. Also NFS
datastores to the appliance do not get unmounted as another side-effect.
Solution:
To solve the issue of having unmounted datastore left behind as well as
ensure reboot host succeeds, we need to ensure maintenance mode is set
on the host before we kick off software updates.
=> ASM-7784 Ensure host is in maintenance mode before starting updates

lib/puppet/provider/esx_software_update/default.rb
Background:
ESX deployed on SD card seems to take over 3 minutes to install VIBs using
esxcli. Current approach of iteratively installing one VIB or ZIP using
esxcli seems to drastically slow down VIB updates on such setup.
Solution:
If transport is from ESX connection, the esxcli operation on such connection
can allow passing multiple VIBs or depots at the same time. We make use of
this feature to install all ZIPs in one-shot, and all VIBs in another shot.
Therefore, this cuts down the install VIB time by N times, where N is the
number of components to update.
We, however, preserver the existing behavior of one VIB or ZIP at a time,
for vCenter based connections, since esxcli operation exposed by vCenter
allow only one component to be updated at a time.
=> ASM-7898 Execute VIB updates in single esxcli call for ESX connections

lib/puppet/provider/iscsi_intiator_binding/default.rb
The vcenter puppet module was failing to bind the iscsi adapters
correctly due to the lack of special characters handling before
making the system call.
In order to resolve this, ASM::Util.run_command method was chosen
instead of making system call directly from the provider script.
Additionally, the password was set as an environment variable for
esxcli (VI_PASSWORD) instead of being passed directly. This should
stop the process list from showing the password.
=> ASM-7987 fix iscsi binding provider call to esxcli

lib/puppet/provider/esx_advanced_options/default.rb
Rescue block trying to access Non local variable
'optkey'
Assigning it to global variable
=> ASM-8046 Undefined local variable or method `optkey'

lib/puppet/provider/vc_vsan_network/default.rb
puppet module now expects one or more VSAN port-groups. In case multiple port-groups are received the VSAN Traffic is enabled on each of port-groups
=> ASM-8368 VSAN configs need to move to 2 vmk case vs. one for VSAN network

lib/puppet/provider/vc_vm/default.rb
Previously ASM did not have ability to vreate virtualCD drive to
support os_install via iso image.
This PR will include CD drive while creating vm.
=> ASM-8648: Added CD/DVD drive while creating vm

lib/puppet_x/puppetlabs/transport/rbvmomi_patch.rb
Seems current implementation of vim.close does not logout session gracefully, rather results in a
ManagedObjectNotFound exception and gets ignored silently. To fix this, we override the base 
implementation to do appropriate logout operation, and then do the original implementation.
=> ASM-9275 Better handling of VIM connection close

bin/discovery.rb
Captured existing settings of server's syslog and cluster HA configuration so that during retry host / cluster configuration can be updated accordingly. Need to skip reconfiguration any parameter which is updated by the user manually.
=> ASM-8838 ESXi helper methods to check for existing VDS and Distributed port-group information

bin/discovery.rb
VMware ESXi discovery is failing when there are one or more host in non-responding state. Added code logic to skip port-group information in case hosts are in non-responding state
=> ASM-9481 Windows 2008 R2 VM Deployment on VDS Cluster Fails with NilClass error

lib/puppet/provider/vc_vm/default.rb
For ScaleIO cluster, each host (with scale io enabled) will need
a SVM that has PCI passthrough for the HBA device. This commit,
along with LUD-37, enable that requirement. This commit focuses
primarily on VM configuration. This is also a pre-req for LUD-134.
=> LUD-133 enable PCI passthrough on VM

lib/puppet/provider/vc_vm/default.rb
VM was going in add NFS ISO loop instead of disconnect ISO loop due to incorrect NULL value check
=> VM getting shutdown during retry

bin/discovery.rb
Adding in hostname and IPs to inventory for VMs
=> LUD-625 Additional data needed to support Brownfield service FW update with ScaleIO nodes

lib/puppet/provider/vc_vm/default.rb
Hiding the password in the logged string.
=> LUD-1567 vCenter credentials logged in puppet output

lib/puppet/provider/vc_vm/default.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
Added ability to apply VM memory and cpu number to deployed OVF.
=> VXFM-1648 ASM-deployer change to configure SVM settings to meet best practice requirement

lib/puppet/provider/vc_vm/default.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
Reverts dell-asm/vmware-vcenter#223
=> Revert "VXFM-1648 ASM-deployer change to configure SVM settings to meet best practice requirement"

lib/puppet/provider/vc_vm/default.rb
Works around issue where an empty template is passed as well as the
OVF URL.
=> VXFM-1647 Prefer creating OVF to template

lib/puppet/provider/vc_vm/default.rb, lib/puppet_x/puppetlabs/transport/rbvmomi_patch.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
This PR also removes patch for close method that is causing failures.
=> vxfm-2080 Fixes unmounting cd ROM after svm configuration.

lib/puppet/provider/esx_vmknic_type/default.rb
After the last change in asm-deployer to enable tcp/ip stack for
vMotion network, retries are failing. To fix this, esx_vmknic_type
provider has been updated to skip creation of vmknic with default
tcp/ip stack if the target vmknic already exists with specific
tcp/ip stack configuration.
=> VXFM-1642 patch vcenter module to handle tcp/ip stack

bin/discovery.rb
Added OS Ip address to vCenter inventory.
=> VXFM-1374  Gather port view information during brownfield server creation

bin/discovery.rb
=> VXFM-1691 Add Mac address to VMNic mapping

bin/discovery.rb
Avoid collecting distributed port-group information for all servers in each iteration
=> VXFM-2880 Discovery script is taking long

lib/puppet/provider/vc_vm/default.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
Change order networks are applied to nic devices to ensure that flex mgmt network is first in the SVM
os.
=> VXFM-2368 SVM NICs not in consistent order

lib/puppet/provider/esx_vmknic/default.rb
For VMNIC creation, there is a possibility of multiple NICs getting created in parallel. VMNIC ID is retreived based on the previously existing VMKNIC. In case two operations gets the same VMKNIC, then one of the operation will fail.
Added a delay and retry for VMNIC creation to avoid failure during initiatial VMKNIC create operation.
Possibility of this error is remote but this generally leads to the failure of whole puppet agent run.
=> VXFM-3187 Management vmnic migration failure

lib/puppet/provider/vc_host/default.rb, lib/puppet/type/vc_host.rb
Updated default power profile to high-performance
=> VXFM-5902 ESXi Power Mangement should be set to High-Performance

lib/puppet/provider/vc_vm/default.rb, lib/puppet/type/vc_vm.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
asm-deployer PR: https://github.com/dell-asm/asm-deployer/pull/2915
asm PR: dell-asm/asm#414
rbmomi PR: dell-asm/rbvmomi#5
asm-automation PR: dell-asm/asm-automation#943
=> VXFM-6641 Backend asm-deployer and puppet work to support HCI compression

lib/puppet/provider/vc_vm/default.rb, lib/puppet/type/vc_vm.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
Related PR: https://github.com/dell-asm/asm/pull/418
=> VXFM-6887 Fix HCI Compression PMEM volume alarm status

lib/puppet/type/vc_vm.rb
@sushilrai @saxens7 
Please review it .
=> VXFM-6929 : NVMe RDM Backend - Disable PCI passthrough

lib/puppet/provider/vc_vm_rdm/default.rb
@saxens7 @gavin-scott @sushilrai   Can you please review and merge?
=> VXFM-7669 - RDM Drive replacement operation

bin/discovery.rb
Based on the performance profiling removed calls made to vCenter SDK for getting same informaiton multiple times. This has improved the discovery time on development setup with 7 hosts by ~15 seconds. (from 45 seconds to 28) seconds
=> VXFM-7666 Continue improving vcenter inventory script time

lib/puppet/provider/vc_dvswitch/default.rb, lib/puppet/provider/vc_dvswitch_migrate/default.rb, lib/puppet/type/vc_dvswitch.rb, lib/puppet/type/vc_dvswitch_migrate.rb, manifests/dvswitch.pp, manifests/vc_dvswitch_migrate.pp
Should be merged with:
https://github.com/dell-asm/asm-deployer/pull/3164
https://github.com/dell-asm/asm/pull/455
=> VXFM-8364 Backend code to configure the LACP port channel for 100Gb deployment

bin/discovery.rb
Added informaiton of the VLAN from the NSX distributed port-groups
Should be merged with https://github.com/dell-asm/asm-core/pull/5502
=> VXFM-9018 NSX-T Disovery support

bin/discovery.rb
Added informaiton of the VLAN from the NSX distributed port-groups
include uplink information
=> [DNM] VXFM-9674 NSX-T Disovery support

bin/discovery.rb
Ensure is_local attribute is included on all host datastores.
=> VXFM-9693 Backend code to move VxFlex GW VM to shared storage

lib/puppet/provider/vc_vm/default.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
@gavin-scott @sushilrai @saxens7 
Please review and merge
=> VXFM-10095:Allow special character for Portgroup and VDS names

bin/discovery.rb
VXFM-10425 add static routes in the host inventory during vcenter discovery
=> VXFM-10425 add static routes in the host inventory during vcenter discovery

lib/puppet/provider/vc_vm/default.rb
@sushilrai @gavin-scott Please review and merge.
=> VXFM-9292 Changes to support VM deployment of CLC,Flexos gateway,Presentation server

lib/puppet/provider/vc_vm/default.rb, spec/unit/puppet/provider/vc_vm/vc_vm_spec.rb
@gavin-scott 
Please review and merge
=> VXFM-10630:undefined method match for array

lib/puppet/provider/esx_datastore/default.rb, lib/puppet/type/esx_datastore.rb
@sushilrai , @gavin-scott 
Hi,
Please review and merge.
Thanks
=> VXFM-10032:Resize Datastore (Volume) for CO service
